# Generated by Django 3.1.3 on 2020-11-24 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='date_created',
            new_name='date_updated',
        ),
    ]
